---
# yaml-language-server: $schema=https://raw.githubusercontent.com/hadolint/hadolint/master/contrib/hadolint.json

ignored:
  - DL3009 # info: Delete the apt lists (/var/lib/apt/lists) after installing something
  - DL3008 # warning: Pin versions in apt get install. Use `apt-get install <package>=<version>`
  - DL4006 # warning: Set the SHELL option -o pipefail before RUN with a pipe in it.
